# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PochtaBlockchain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PochtaBlockchain

	pod "FlagPhoneNumber"
	pod "Firebase"
	pod "Firebase\Auth"

end
